services:

  citus-coordinator:
    image: citusdata/citus:13.2
    container_name: citus-coordinator
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: my_distributed_db
    volumes:
      - citus_coordinator_data:/var/lib/postgresql/data
    restart: unless-stopped

  citus-worker1:
    image: citusdata/citus:13.2
    container_name: citus-worker1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: my_distributed_db
    volumes:
      - citus_worker1_data:/var/lib/postgresql/data
    restart: unless-stopped

  citus-worker2:
    image: citusdata/citus:13.2
    container_name: citus-worker2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: my_distributed_db
    volumes:
      - citus_worker2_data:/var/lib/postgresql/data
    restart: unless-stopped

  citus-worker3:
    image: citusdata/citus:13.2
    container_name: citus-worker3
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: my_distributed_db
    volumes:
      - citus_worker3_data:/var/lib/postgresql/data
    restart: unless-stopped

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - citus-coordinator
    command:
      - -url=jdbc:postgresql://citus-coordinator:5432/my_distributed_db
      - -user=postgres
      - -password=postgrespassword
      - migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  citus_coordinator_data:
  citus_worker1_data:
  citus_worker2_data:
  citus_worker3_data: